apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: price
    namespace: xbos
    labels:
        app: price
spec:
    replicas: 1
    selector:
        matchLabels:
            app: price
    template:
        metadata:
            labels:
                app: price
        spec:
            volumes:
                - name: data
                  hostPath:
                    path: /etc/xbos-microservices/price
            containers:
                - name: service
                  image:  xbos/microsvc_price:latest
                  imagePullPolicy: Always
                  env:
                      - name: PRICE_HOST_ADDRESS
                        value: "0.0.0.0:50066"
                      - name: PRICE_DATA_PATH
                        value: "/data"
                      - name: MORTAR_API_USERNAME
                        value: "<here>"
                      - name: MORTAR_API_PASSWORD
                        value: "<here>"
                  volumeMounts:
                      - name: data
                        mountPath: /data
                  ports:
                    - containerPort: 50066
---
kind: Service
apiVersion: v1
metadata:
    name: price
    namespace: xbos
spec:
    type: ClusterIP
    #externalIPs:
    #- << ip address here >>
    selector:
        app: price
    ports:
      - name: grpc
        port: 5000
        protocol: TCP
        targetPort: 50066


