apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: discomfort
    namespace: xbos
    labels:
        app: discomfort
spec:
    replicas: 1
    selector:
        matchLabels:
            app: discomfort
    template:
        metadata:
            labels:
                app: discomfort
        spec:
            containers:
                - name: service
                  image:  xbos/microsvc_discomfort:latest
                  imagePullPolicy: Always
                  env:
                      - name: DISCOMFORT_HOST_ADDRESS
                        value: "0.0.0.0:50066"
                  ports:
                    - containerPort: 50066
---
kind: Service
apiVersion: v1
metadata:
    name: discomfort
    namespace: xbos
spec:
    type: ClusterIP
    #externalIPs:
    #- << ip address here >>
    selector:
        app: discomfort
    ports:
      - name: grpc
        port: 5000
        protocol: TCP
        targetPort: 50066


