apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: indoor-temperature-prediction
    namespace: xbos
    labels:
        app: indoor-temperature-prediction
spec:
    replicas: 1
    selector:
        matchLabels:
            app: indoor-temperature-prediction
    template:
        metadata:
            labels:
                app: indoor-temperature-prediction
        spec:
            volumes:
                - name: data
                  hostPath:
                    path: /etc/xbos-microservices/indoor_temperature_prediction
            containers:
                - name: service
                  image:  xbos/microsvc_indoor_temperature_prediction:latest
                  imagePullPolicy: Always
                  env:
                      - name: BUILDING_ZONE_NAMES_HOST_ADDRESS
                        value: "k8ms.xbos.io:9001"
                      - name: INDOOR_DATA_HISTORICAL_HOST_ADDRESS
                        value: "k8ms.xbos.io:9001"
                      - name: INDOOR_TEMPERATURE_PREDICTION_HOST_ADDRESS
                        value: "0.0.0.0:50066"
                  ports:
                    - containerPort: 50066
---
kind: Service
apiVersion: v1
metadata:
    name: indoor-temperature-prediction
    namespace: xbos
spec:
    type: ClusterIP
    #externalIPs:
    #- << ip address here >>
    selector:
        app: indoor-temperature-prediction
    ports:
      - name: grpc
        port: 5000
        protocol: TCP
        targetPort: 50066


