apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: outdoor-temperature-historical
    namespace: xbos
    labels:
        app: outdoor-temperature-historical
spec:
    replicas: 1
    selector:
        matchLabels:
            app: outdoor-temperature-historical
    template:
        metadata:
            labels:
                app: outdoor-temperature-historical
        spec:
            containers:
                - name: service
                  image:  xbos/microsvc_outdoor_temperature_historical:latest
                  imagePullPolicy: Always
                  env:
                      - name: OUTDOOR_TEMPERATURE_HISTORICAL_HOST_ADDRESS
                        value: "0.0.0.0:50066"
                      - name: MORTAR_API_USERNAME
                        value: "<here>"
                      - name: MORTAR_API_PASSWORD
                        value: "<here>"
                  ports:
                    - containerPort: 50066
---
kind: Service
apiVersion: v1
metadata:
    name: outdoor-temperature-historical
    namespace: xbos
spec:
    type: ClusterIP
    #externalIPs:
    #- << ip address here >>
    selector:
        app: outdoor-temperature-historical
    ports:
      - name: grpc
        port: 5000
        protocol: TCP
        targetPort: 50066


